<?php

use App\Http\Controllers\Inventory\StockAdjustmentController;
use App\Http\Controllers\Inventory\StockOverviewController;
use App\Http\Controllers\Inventory\StockTransferController;
use App\Http\Controllers\People\UserController;
use App\Http\Controllers\POS\DashboardController;
use App\Http\Controllers\POS\ModulesController;
use App\Http\Controllers\POS\SalesController;
use App\Http\Controllers\Products\BarcodeController;
use App\Http\Controllers\Products\BrandController;
use App\Http\Controllers\Products\CategoryController;
use App\Http\Controllers\Products\ProductController;
use App\Http\Controllers\Products\TaxRateController;
use App\Http\Controllers\Products\UnitController;
use App\Http\Controllers\Settings\RoleController;
use App\Http\Controllers\Settings\WarehouseController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', fn () => Inertia::render('Landing/Index'))->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/system-design', fn () => Inertia::render('SystemDesign/Index'))->name('system-design');
    Route::get('/pos', [SalesController::class, 'pos'])->name('pos');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/new', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/barcode', [BarcodeController::class, 'index'])->name('products.barcode');
    Route::get('/products/categories', [CategoryController::class, 'index'])->name('products.categories');
    Route::get('/products/categories/add', [CategoryController::class, 'create'])->name('products.categories.create');
    Route::post('/products/categories', [CategoryController::class, 'store'])->name('products.categories.store');
    Route::get('/products/categories/{category}/edit', [CategoryController::class, 'edit'])->name('products.categories.edit');
    Route::patch('/products/categories/{category}', [CategoryController::class, 'update'])->name('products.categories.update');
    Route::delete('/products/categories/{category}', [CategoryController::class, 'destroy'])->name('products.categories.destroy');
    Route::get('/products/categories/{category}', [CategoryController::class, 'show'])->name('products.categories.show');
    Route::get('/products/brands', [BrandController::class, 'index'])->name('products.brands');
    Route::get('/products/brands/add', [BrandController::class, 'create'])->name('products.brands.create');
    Route::post('/products/brands', [BrandController::class, 'store'])->name('products.brands.store');
    Route::get('/products/brands/{brand}/edit', [BrandController::class, 'edit'])->name('products.brands.edit');
    Route::patch('/products/brands/{brand}', [BrandController::class, 'update'])->name('products.brands.update');
    Route::delete('/products/brands/{brand}', [BrandController::class, 'destroy'])->name('products.brands.destroy');
    Route::get('/products/brands/{brand}', [BrandController::class, 'show'])->name('products.brands.show');
    Route::get('/products/units', [UnitController::class, 'index'])->name('products.units');
    Route::get('/products/units/add', [UnitController::class, 'create'])->name('products.units.create');
    Route::post('/products/units', [UnitController::class, 'store'])->name('products.units.store');
    Route::get('/products/units/{unit}/edit', [UnitController::class, 'edit'])->name('products.units.edit');
    Route::patch('/products/units/{unit}', [UnitController::class, 'update'])->name('products.units.update');
    Route::delete('/products/units/{unit}', [UnitController::class, 'destroy'])->name('products.units.destroy');
    Route::get('/products/units/{unit}', [UnitController::class, 'show'])->name('products.units.show');
    Route::get('/products/tax-rates', [TaxRateController::class, 'index'])->name('products.tax-rates');
    Route::get('/products/tax-rates/add', [TaxRateController::class, 'create'])->name('products.tax-rates.create');
    Route::post('/products/tax-rates', [TaxRateController::class, 'store'])->name('products.tax-rates.store');
    Route::get('/products/tax-rates/{taxRate}/edit', [TaxRateController::class, 'edit'])->name('products.tax-rates.edit');
    Route::patch('/products/tax-rates/{taxRate}', [TaxRateController::class, 'update'])->name('products.tax-rates.update');
    Route::delete('/products/tax-rates/{taxRate}', [TaxRateController::class, 'destroy'])->name('products.tax-rates.destroy');
    Route::get('/products/tax-rates/{taxRate}', [TaxRateController::class, 'show'])->name('products.tax-rates.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');

    Route::get('/reports/stock', [StockOverviewController::class, 'index'])->name('reports.stock');
    Route::get('/inventory/adjustments', [StockAdjustmentController::class, 'index'])->name('inventory.adjustments');
    Route::get('/inventory/adjustments/add', [StockAdjustmentController::class, 'create'])->name('inventory.adjustments.create');
    Route::post('/inventory/adjustments', [StockAdjustmentController::class, 'store'])->name('inventory.adjustments.store');
    Route::get('/inventory/adjustments/{stockAdjustment}/edit', [StockAdjustmentController::class, 'edit'])->name('inventory.adjustments.edit');
    Route::patch('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'update'])->name('inventory.adjustments.update');
    Route::delete('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'destroy'])->name('inventory.adjustments.destroy');
    Route::get('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'show'])->name('inventory.adjustments.show');
    Route::get('/inventory/transfers', [StockTransferController::class, 'index'])->name('inventory.transfers');
    Route::get('/inventory/transfers/add', [StockTransferController::class, 'create'])->name('inventory.transfers.create');
    Route::post('/inventory/transfers', [StockTransferController::class, 'store'])->name('inventory.transfers.store');
    Route::get('/inventory/transfers/{stockTransfer}/edit', [StockTransferController::class, 'edit'])->name('inventory.transfers.edit');
    Route::patch('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'update'])->name('inventory.transfers.update');
    Route::delete('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'destroy'])->name('inventory.transfers.destroy');
    Route::get('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'show'])->name('inventory.transfers.show');

    Route::get('/people/customers/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'CustomersConfig')->name('people.customers');
    Route::get('/people/suppliers/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'SuppliersConfig')->name('people.suppliers');
    Route::get('/people/users', [UserController::class, 'index'])->name('people.users');
    Route::get('/people/users/add', [UserController::class, 'create'])->name('people.users.create');
    Route::post('/people/users', [UserController::class, 'store'])->name('people.users.store');
    Route::get('/people/users/{user}/edit', [UserController::class, 'edit'])->name('people.users.edit');
    Route::patch('/people/users/{user}', [UserController::class, 'update'])->name('people.users.update');
    Route::patch('/people/users/{user}/status', [UserController::class, 'updateStatus'])->name('people.users.status');
    Route::delete('/people/users/{user}', [UserController::class, 'destroy'])->name('people.users.destroy');
    Route::get('/people/users/{user}', [UserController::class, 'show'])->name('people.users.show');
    Route::get('/people/users/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'UsersConfig')->name('people.users.fallback');
    Route::get('/purchases/return/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'PurchaseReturnsConfig')->name('purchases.return');
    Route::get('/purchases/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'PurchasesConfig')->name('purchases');
    Route::get('/sales/return/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'SaleReturnsConfig')->name('sales.return');
    Route::get('/sales/exchange', fn () => Inertia::render('Modules/Placeholder', ['title' => 'Exchange Portal (Placeholder)']))->name('sales.exchange');
    Route::get('/sales/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'SalesConfig')->name('sales');
    Route::get('/quotations/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'QuotationsConfig')->name('quotations');
    Route::get('/expenses/categories/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'ExpenseCategoriesConfig')->name('expenses.categories');
    Route::get('/expenses/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'ExpensesConfig')->name('expenses');
    Route::get('/accounting/transfer', fn () => Inertia::render('Modules/AccountingPage', ['view' => 'transfer']))->name('accounting.transfer');
    Route::get('/accounting/statement', fn () => Inertia::render('Modules/AccountingPage', ['view' => 'statement']))->name('accounting.statement');
    Route::get('/accounting/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'AccountsConfig')->name('accounting');
    Route::get('/reports/{report}', [ModulesController::class, 'report'])->whereIn('report', ['sales', 'purchases', 'products', 'profit-loss'])->name('reports.show');
    Route::get('/settings/roles', [RoleController::class, 'index'])->name('settings.roles');
    Route::get('/settings/roles/add', [RoleController::class, 'create'])->name('settings.roles.create');
    Route::post('/settings/roles', [RoleController::class, 'store'])->name('settings.roles.store');
    Route::get('/settings/roles/{role}/edit', [RoleController::class, 'edit'])->name('settings.roles.edit');
    Route::patch('/settings/roles/{role}', [RoleController::class, 'update'])->name('settings.roles.update');
    Route::delete('/settings/roles/{role}', [RoleController::class, 'destroy'])->name('settings.roles.destroy');
    Route::get('/settings/roles/{role}', [RoleController::class, 'show'])->name('settings.roles.show');
    Route::get('/settings/roles/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'RolesConfig')->name('settings.roles.fallback');
    Route::get('/settings/warehouses', [WarehouseController::class, 'index'])->name('settings.warehouses');
    Route::get('/settings/warehouses/add', [WarehouseController::class, 'create'])->name('settings.warehouses.create');
    Route::post('/settings/warehouses', [WarehouseController::class, 'store'])->name('settings.warehouses.store');
    Route::get('/settings/warehouses/{warehouse}/edit', [WarehouseController::class, 'edit'])->name('settings.warehouses.edit');
    Route::patch('/settings/warehouses/{warehouse}', [WarehouseController::class, 'update'])->name('settings.warehouses.update');
    Route::delete('/settings/warehouses/{warehouse}', [WarehouseController::class, 'destroy'])->name('settings.warehouses.destroy');
    Route::get('/settings/warehouses/{warehouse}', [WarehouseController::class, 'show'])->name('settings.warehouses.show');
    Route::get('/settings/warehouses/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'WarehousesConfig')->name('settings.warehouses.fallback');
    Route::get('/settings/audit-logs/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'AuditLogsConfig')->name('settings.audit-logs');
    Route::get('/settings/notifications', fn () => Inertia::render('Modules/Placeholder', ['title' => 'Notifications (Placeholder)']))->name('settings.notifications');
    Route::get('/settings', fn () => Inertia::render('Modules/SettingsPage'))->name('settings');
});

require __DIR__.'/auth.php';
