<?php

use App\Http\Controllers\Accounting\AccountController;
use App\Http\Controllers\Accounting\MoneyTransferController;
use App\Http\Controllers\Expenses\ExpenseCategoryController;
use App\Http\Controllers\Expenses\ExpenseController;
use App\Http\Controllers\Inventory\StockAdjustmentController;
use App\Http\Controllers\Inventory\StockTransferController;
use App\Http\Controllers\People\CustomerController;
use App\Http\Controllers\People\CustomerGroupController;
use App\Http\Controllers\People\SupplierController;
use App\Http\Controllers\People\UserController;
use App\Http\Controllers\POS\DashboardController;
use App\Http\Controllers\POS\ModulesController;
use App\Http\Controllers\Products\BarcodeController;
use App\Http\Controllers\Products\BrandController;
use App\Http\Controllers\Products\CategoryController;
use App\Http\Controllers\Products\ProductController;
use App\Http\Controllers\Products\TaxRateController;
use App\Http\Controllers\Products\UnitController;
use App\Http\Controllers\Purchases\PurchaseController;
use App\Http\Controllers\Purchases\PurchasePaymentController;
use App\Http\Controllers\Purchases\PurchaseReturnController;
use App\Http\Controllers\Reports\ReportController;
use App\Http\Controllers\Sales\HeldSaleController;
use App\Http\Controllers\Sales\POSController;
use App\Http\Controllers\Sales\QuotationController;
use App\Http\Controllers\Sales\SaleController;
use App\Http\Controllers\Sales\SaleReturnController;
use App\Http\Controllers\Sales\SaleTransactionController;
use App\Http\Controllers\Settings\RoleController;
use App\Http\Controllers\Settings\WarehouseController;
use App\Http\Controllers\System\AuditLogController;
use App\Http\Controllers\System\NotificationController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', fn () => Inertia::render('Landing/Index'))->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/system-design', fn () => Inertia::render('SystemDesign/Index'))->name('system-design');
    Route::get('/pos', [POSController::class, 'index'])->name('pos');
    Route::post('/pos/sale', [SaleTransactionController::class, 'store'])->name('pos.sales.store');
    Route::get('/pos/held', [HeldSaleController::class, 'index'])->name('pos.held.index');
    Route::post('/pos/held', [HeldSaleController::class, 'store'])->name('pos.held.store');
    Route::delete('/pos/held/{heldSale}', [HeldSaleController::class, 'destroy'])->name('pos.held.destroy');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/new', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/barcode', [BarcodeController::class, 'index'])->name('products.barcode');
    Route::get('/products/categories', [CategoryController::class, 'index'])->name('products.categories');
    Route::get('/products/categories/add', [CategoryController::class, 'create'])->name('products.categories.create');
    Route::post('/products/categories', [CategoryController::class, 'store'])->name('products.categories.store');
    Route::get('/products/categories/{category}/edit', [CategoryController::class, 'edit'])->name('products.categories.edit');
    Route::patch('/products/categories/{category}', [CategoryController::class, 'update'])->name('products.categories.update');
    Route::delete('/products/categories/{category}', [CategoryController::class, 'destroy'])->name('products.categories.destroy');
    Route::get('/products/categories/{category}', [CategoryController::class, 'show'])->name('products.categories.show');
    Route::get('/products/brands', [BrandController::class, 'index'])->name('products.brands');
    Route::get('/products/brands/add', [BrandController::class, 'create'])->name('products.brands.create');
    Route::post('/products/brands', [BrandController::class, 'store'])->name('products.brands.store');
    Route::get('/products/brands/{brand}/edit', [BrandController::class, 'edit'])->name('products.brands.edit');
    Route::patch('/products/brands/{brand}', [BrandController::class, 'update'])->name('products.brands.update');
    Route::delete('/products/brands/{brand}', [BrandController::class, 'destroy'])->name('products.brands.destroy');
    Route::get('/products/brands/{brand}', [BrandController::class, 'show'])->name('products.brands.show');
    Route::get('/products/units', [UnitController::class, 'index'])->name('products.units');
    Route::get('/products/units/add', [UnitController::class, 'create'])->name('products.units.create');
    Route::post('/products/units', [UnitController::class, 'store'])->name('products.units.store');
    Route::get('/products/units/{unit}/edit', [UnitController::class, 'edit'])->name('products.units.edit');
    Route::patch('/products/units/{unit}', [UnitController::class, 'update'])->name('products.units.update');
    Route::delete('/products/units/{unit}', [UnitController::class, 'destroy'])->name('products.units.destroy');
    Route::get('/products/units/{unit}', [UnitController::class, 'show'])->name('products.units.show');
    Route::get('/products/tax-rates', [TaxRateController::class, 'index'])->name('products.tax-rates');
    Route::get('/products/tax-rates/add', [TaxRateController::class, 'create'])->name('products.tax-rates.create');
    Route::post('/products/tax-rates', [TaxRateController::class, 'store'])->name('products.tax-rates.store');
    Route::get('/products/tax-rates/{taxRate}/edit', [TaxRateController::class, 'edit'])->name('products.tax-rates.edit');
    Route::patch('/products/tax-rates/{taxRate}', [TaxRateController::class, 'update'])->name('products.tax-rates.update');
    Route::delete('/products/tax-rates/{taxRate}', [TaxRateController::class, 'destroy'])->name('products.tax-rates.destroy');
    Route::get('/products/tax-rates/{taxRate}', [TaxRateController::class, 'show'])->name('products.tax-rates.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');

    Route::get('/inventory/adjustments', [StockAdjustmentController::class, 'index'])->name('inventory.adjustments');
    Route::get('/inventory/adjustments/add', [StockAdjustmentController::class, 'create'])->name('inventory.adjustments.create');
    Route::post('/inventory/adjustments', [StockAdjustmentController::class, 'store'])->name('inventory.adjustments.store');
    Route::get('/inventory/adjustments/{stockAdjustment}/edit', [StockAdjustmentController::class, 'edit'])->name('inventory.adjustments.edit');
    Route::patch('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'update'])->name('inventory.adjustments.update');
    Route::delete('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'destroy'])->name('inventory.adjustments.destroy');
    Route::get('/inventory/adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'show'])->name('inventory.adjustments.show');
    Route::get('/inventory/transfers', [StockTransferController::class, 'index'])->name('inventory.transfers');
    Route::get('/inventory/transfers/add', [StockTransferController::class, 'create'])->name('inventory.transfers.create');
    Route::post('/inventory/transfers', [StockTransferController::class, 'store'])->name('inventory.transfers.store');
    Route::get('/inventory/transfers/{stockTransfer}/edit', [StockTransferController::class, 'edit'])->name('inventory.transfers.edit');
    Route::patch('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'update'])->name('inventory.transfers.update');
    Route::delete('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'destroy'])->name('inventory.transfers.destroy');
    Route::get('/inventory/transfers/{stockTransfer}', [StockTransferController::class, 'show'])->name('inventory.transfers.show');

    Route::get('/people/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::post('/people/customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/people/customers/{customer}/edit', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::patch('/people/customers/{customer}', [CustomerController::class, 'update'])->name('customers.update');
    Route::delete('/people/customers/{customer}', [CustomerController::class, 'destroy'])->name('customers.destroy');
    Route::get('/people/customers/{customer}', [CustomerController::class, 'show'])->name('customers.show');
    Route::get('/people/customer-groups', [CustomerGroupController::class, 'index'])->name('customer-groups.index');
    Route::post('/people/customer-groups', [CustomerGroupController::class, 'store'])->name('customer-groups.store');
    Route::patch('/people/customer-groups/{customerGroup}', [CustomerGroupController::class, 'update'])->name('customer-groups.update');
    Route::delete('/people/customer-groups/{customerGroup}', [CustomerGroupController::class, 'destroy'])->name('customer-groups.destroy');
    Route::get('/people/suppliers', [SupplierController::class, 'index'])->name('suppliers.index');
    Route::post('/people/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
    Route::get('/people/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->name('suppliers.edit');
    Route::patch('/people/suppliers/{supplier}', [SupplierController::class, 'update'])->name('suppliers.update');
    Route::delete('/people/suppliers/{supplier}', [SupplierController::class, 'destroy'])->name('suppliers.destroy');
    Route::get('/people/suppliers/{supplier}', [SupplierController::class, 'show'])->name('suppliers.show');
    Route::get('/people/users', [UserController::class, 'index'])->name('people.users');
    Route::get('/people/users/add', [UserController::class, 'create'])->name('people.users.create');
    Route::post('/people/users', [UserController::class, 'store'])->name('people.users.store');
    Route::get('/people/users/{user}/edit', [UserController::class, 'edit'])->name('people.users.edit');
    Route::patch('/people/users/{user}', [UserController::class, 'update'])->name('people.users.update');
    Route::patch('/people/users/{user}/status', [UserController::class, 'updateStatus'])->name('people.users.status');
    Route::delete('/people/users/{user}', [UserController::class, 'destroy'])->name('people.users.destroy');
    Route::get('/people/users/{user}', [UserController::class, 'show'])->name('people.users.show');
    Route::get('/people/users/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'UsersConfig')->name('people.users.fallback');
    Route::get('/purchases/returns', [PurchaseReturnController::class, 'index'])->name('purchase-returns.index');
    Route::get('/purchases/returns/create', [PurchaseReturnController::class, 'create'])->name('purchase-returns.create');
    Route::post('/purchases/returns', [PurchaseReturnController::class, 'store'])->name('purchase-returns.store');
    Route::delete('/purchases/returns/{purchaseReturn}', [PurchaseReturnController::class, 'destroy'])->name('purchase-returns.destroy');
    Route::get('/purchases/returns/{purchaseReturn}', [PurchaseReturnController::class, 'show'])->name('purchase-returns.show');
    Route::get('/purchases', [PurchaseController::class, 'index'])->name('purchases.index');
    Route::get('/purchases/create', [PurchaseController::class, 'create'])->name('purchases.create');
    Route::post('/purchases', [PurchaseController::class, 'store'])->name('purchases.store');
    Route::post('/purchases/{purchase}/payments', [PurchasePaymentController::class, 'store'])->name('purchases.payments.store');
    Route::get('/purchases/{purchase}/edit', [PurchaseController::class, 'edit'])->name('purchases.edit');
    Route::patch('/purchases/{purchase}', [PurchaseController::class, 'update'])->name('purchases.update');
    Route::delete('/purchases/{purchase}', [PurchaseController::class, 'destroy'])->name('purchases.destroy');
    Route::get('/purchases/{purchase}', [PurchaseController::class, 'show'])->name('purchases.show');
    Route::get('/sales/returns', [SaleReturnController::class, 'index'])->name('sale-returns.index');
    Route::post('/sales/returns', [SaleReturnController::class, 'store'])->name('sale-returns.store');
    Route::delete('/sales/returns/{saleReturn}', [SaleReturnController::class, 'destroy'])->name('sale-returns.destroy');
    Route::get('/sales/returns/{saleReturn}', [SaleReturnController::class, 'show'])->name('sale-returns.show');
    Route::get('/sales/exchange', fn () => Inertia::render('Modules/Placeholder', ['title' => 'Exchange Portal (Placeholder)']))->name('sales.exchange');
    Route::get('/sales', [SaleController::class, 'index'])->name('sales.index');
    Route::delete('/sales/{sale}', [SaleController::class, 'destroy'])->name('sales.destroy');
    Route::get('/sales/{sale}', [SaleController::class, 'show'])->name('sales.show');
    Route::get('/quotations', [QuotationController::class, 'index'])->name('quotations.index');
    Route::post('/quotations', [QuotationController::class, 'store'])->name('quotations.store');
    Route::patch('/quotations/{quotation}', [QuotationController::class, 'update'])->name('quotations.update');
    Route::post('/quotations/{quotation}/convert', [QuotationController::class, 'convertToSale'])->name('quotations.convert');
    Route::delete('/quotations/{quotation}', [QuotationController::class, 'destroy'])->name('quotations.destroy');
    Route::get('/quotations/{quotation}', [QuotationController::class, 'show'])->name('quotations.show');
    Route::get('/expenses/categories', [ExpenseCategoryController::class, 'index'])->name('expenses.categories.index');
    Route::post('/expenses/categories', [ExpenseCategoryController::class, 'store'])->name('expenses.categories.store');
    Route::patch('/expenses/categories/{expenseCategory}', [ExpenseCategoryController::class, 'update'])->name('expenses.categories.update');
    Route::delete('/expenses/categories/{expenseCategory}', [ExpenseCategoryController::class, 'destroy'])->name('expenses.categories.destroy');
    Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses.index');
    Route::post('/expenses', [ExpenseController::class, 'store'])->name('expenses.store');
    Route::patch('/expenses/{expense}', [ExpenseController::class, 'update'])->name('expenses.update');
    Route::delete('/expenses/{expense}', [ExpenseController::class, 'destroy'])->name('expenses.destroy');
    Route::get('/expenses/{expense}', [ExpenseController::class, 'show'])->name('expenses.show');
    Route::get('/accounting/accounts', [AccountController::class, 'index'])->name('accounts.index');
    Route::post('/accounting/accounts', [AccountController::class, 'store'])->name('accounts.store');
    Route::patch('/accounting/accounts/{account}', [AccountController::class, 'update'])->name('accounts.update');
    Route::delete('/accounting/accounts/{account}', [AccountController::class, 'destroy'])->name('accounts.destroy');
    Route::get('/accounting/accounts/{account}/statement', [AccountController::class, 'statement'])->name('accounts.statement');
    Route::get('/accounting/accounts/{account}', [AccountController::class, 'show'])->name('accounts.show');
    Route::get('/accounting/transfers', [MoneyTransferController::class, 'index'])->name('money-transfers.index');
    Route::post('/accounting/transfers', [MoneyTransferController::class, 'store'])->name('money-transfers.store');
    Route::delete('/accounting/transfers/{moneyTransfer}', [MoneyTransferController::class, 'destroy'])->name('money-transfers.destroy');
    Route::get('/accounting/transfers/{moneyTransfer}', [MoneyTransferController::class, 'show'])->name('money-transfers.show');
    Route::get('/reports/sales', [ReportController::class, 'sales'])->name('reports.sales');
    Route::get('/reports/purchases', [ReportController::class, 'purchases'])->name('reports.purchases');
    Route::get('/reports/products', [ReportController::class, 'products'])->name('reports.products');
    Route::get('/reports/stock', [ReportController::class, 'stock'])->name('reports.stock');
    Route::get('/reports/profit-loss', [ReportController::class, 'profitLoss'])->name('reports.profit-loss');
    Route::get('/reports/expenses', [ReportController::class, 'expenses'])->name('reports.expenses');
    Route::get('/settings/roles', [RoleController::class, 'index'])->name('settings.roles');
    Route::get('/settings/roles/add', [RoleController::class, 'create'])->name('settings.roles.create');
    Route::post('/settings/roles', [RoleController::class, 'store'])->name('settings.roles.store');
    Route::get('/settings/roles/{role}/edit', [RoleController::class, 'edit'])->name('settings.roles.edit');
    Route::patch('/settings/roles/{role}', [RoleController::class, 'update'])->name('settings.roles.update');
    Route::delete('/settings/roles/{role}', [RoleController::class, 'destroy'])->name('settings.roles.destroy');
    Route::get('/settings/roles/{role}', [RoleController::class, 'show'])->name('settings.roles.show');
    Route::get('/settings/roles/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'RolesConfig')->name('settings.roles.fallback');
    Route::get('/settings/warehouses', [WarehouseController::class, 'index'])->name('settings.warehouses');
    Route::get('/settings/warehouses/add', [WarehouseController::class, 'create'])->name('settings.warehouses.create');
    Route::post('/settings/warehouses', [WarehouseController::class, 'store'])->name('settings.warehouses.store');
    Route::get('/settings/warehouses/{warehouse}/edit', [WarehouseController::class, 'edit'])->name('settings.warehouses.edit');
    Route::patch('/settings/warehouses/{warehouse}', [WarehouseController::class, 'update'])->name('settings.warehouses.update');
    Route::delete('/settings/warehouses/{warehouse}', [WarehouseController::class, 'destroy'])->name('settings.warehouses.destroy');
    Route::get('/settings/warehouses/{warehouse}', [WarehouseController::class, 'show'])->name('settings.warehouses.show');
    Route::get('/settings/warehouses/{path?}', [ModulesController::class, 'crud'])->where('path', '.*')->defaults('config', 'WarehousesConfig')->name('settings.warehouses.fallback');
    Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::patch('/notifications/{notification}/read', [NotificationController::class, 'markAsRead'])->name('notifications.read');
    Route::get('/settings/audit-logs', [AuditLogController::class, 'index'])->name('settings.audit-logs');
    Route::get('/settings/notifications', [NotificationController::class, 'index'])->name('settings.notifications');
    Route::get('/settings', fn () => Inertia::render('Modules/SettingsPage'))->name('settings');
});

require __DIR__.'/auth.php';
